### PR TITLE
backbone:all shouldn't invoke backbone:app, fixes #214

### LINKED ISSUE #214: yo backbone:all - Does not work how it should
**Input:**

```
$ yo backbone:all Posts
```

**Output:**

```
   create app/scripts/models
   create app/scripts/collections
   create app/scripts/views
   create app/scripts/routes
   create app/scripts/helpers
   create app/scripts/templates
   invoke   backbone:app:/usr/local/lib/node_modules/generator-backbone/all/index.js

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I include HTML5 Boilerplate, jQuery, Backbone.js and Modernizr.
[?] What more would you like? (Press <space> to select)
❯⬢ Twitter Bootstrap for Sass
 ⬡ Use CoffeeScript
 ⬡ Use RequireJs
```

**Expected:**

The expectation is that the `yo backbone` generator should invoke the following:

1. `backbone:model Post` - Create 1 `models/Post.js` model.
2. `backbone:collection Posts` - Create 1 `collections/Posts.js` collection.
3. `backbone:view Posts` - Create 1 `views/Posts.js` & `templates/Posts.ejs` view for displaying an array of `Post` models.
4. `backbone:view Post` - Create 1 `views/Post.js` & `templates/Post.ejs` view for displaying a single `Post` model.
5. `backbone:router Posts` - Create 1 `routers/Posts.js` router  with route `#/posts` rendering the `Posts` view and `#/post/:ID` rendering the `Post` view.

**Summary:**

I will look into the generator-backbone code and see if I can contribute and solve this issue. If this is not the correct expectation, then please do provide a description on what the expectation is.

### PR DESCRIPTION
**Pull request by ruyadorno**
`backbone:all` had this weird composition where it would try to invoke `backbone:app`, that would just completely break the expected behavior as described on #214 

This PR fixes it by just removing the rogue composition with `backbone:app` altogether.

@arthurvr

### CODE REVIEW

**Comment by arthurvr** [comment]
Needs a rebase. For the rest this looks reasonable. Thanks!

**Comment by ruyadorno** [comment]
:+1:

**Comment by ruyadorno** [comment]
also added tests for `backbone:all`, let's make sure we keep this working in the future :wink:

File: test/test-foo.js [hunk 1]
```diff
@@ -110,4 +110,44 @@ describe('Backbone generator test', function () {
...
+              testDepsBeenCalled();
+            }
+          }),
+          name
+        ];
+      });
+
+      // tests that all dependencies have been called, will timeout otherwise
+      var testDepsBeenCalled = function () {
+          var allDepsCalled = depNames.every(function (name) {
```
Comment (arthurvr) [inline test/test-foo.js]: Wrong indentation.

File: test/test-foo.js [hunk 2]
```diff
@@ -110,4 +110,44 @@ describe('Backbone generator test', function () {
     });
   });
 
+  describe('creates backbone all', function () {
```
Comment (arthurvr) [inline test/test-foo.js]: Shouldn't this be `creates backbone:all`?

Comment (arthurvr) [inline test/test-foo.js]: Oh, I see. It's consistent with the other spec naming. Alright.

**Comment by arthurvr** [comment]
Cool work!

File: test/test-foo.js (hunk 1 above)
Comment (ruyadorno) [inline test/test-foo.js]: oopsie, fixed

**Comment by ruyadorno** [comment]
this should be good to merge now :blush:
