### PR TITLE
fixes #378 404 main css, main.js

### LINKED ISSUE #378: 404 main css, main.js
Hello people. I installed Backbone.js generator <code>yo backbone my-app</code> After i generated view <code>backbone:view blog</code>. Then i run <code>grunt server</code> and i see my app in http://localhost:9000/ cool! =) But if i will write in my view - 'blog' anything. For example write - <code> console.log('init my view');</code> in initialize: method my view.  I have errors - 
<code>
Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:4 Uncaught ReferenceError: Invalid left-hand side in assignment
http://localhost:9000/scripts/templates.js Failed to load resource: the server responded with a status of 404 (Not Found)
video.js:3 Uncaught ReferenceError: VodBackboneGenerator is not defined
http://localhost:9000/styles/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
</code>

If stop <code>grunt server</code> and run again, the errors will not be.

Screen photo - http://screencast.com/t/huSQwcRP
Screen video - http://screencast.com/t/yzWi7FNj

### PR DESCRIPTION
**Pull request by mteodori**
incorrect generated app name in main when a dash is used

### CODE REVIEW

File: generators/app/index.js [hunk 1]
```diff
@@ -163,7 +163,7 @@ var BackboneGenerator = yeoman.generators.Base.extend({
         this.destinationPath('.jshintrc'),
         {
           appName: this.appname,
-          appSlugName: paramCase(this.appname),
+          appSlugName: pascalCase(this.appname),
```
Comment (ruyadorno) [inline generators/app/index.js]: the name `appSlugName` was just used because it referred to a [different module](https://www.npmjs.com/package/to-slug-case) we were using here at first, now that you're on it, it would be actually nice to replace it to something that makes more sense, maybe `appPascalCaseName` ?

we need to change both here and in the `jshintrc` template file :blush:

Comment (mteodori) [inline generators/app/index.js]: ok for me, didn't know about the history behind the variable name :)

**Comment by ruyadorno** [comment]
:+1: great!

many thanks for all the awesome PRs :tada:
